version: '3.9'
services:
  bot:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    links:
      - db
  db:
    image: postgres:13.1
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432'
    volumes:
      - postgres-db:/var/lib/postgres
volumes:
  postgres-db:
    external: true
